CLASS zcl_eit1_tstmp DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES zif_eit1_tstmp.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_eit1_tstmp IMPLEMENTATION.
  METHOD zif_eit1_tstmp~get.
    GET TIME STAMP FIELD rv_tstmp.
  ENDMETHOD.

ENDCLASS.
