CLASS zcx_eit1_xml_exception DEFINITION
  PUBLIC
  INHERITING FROM zcx_eit1_exception
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcx_eit1_xml_exception IMPLEMENTATION.
ENDCLASS.
